### ISSUE TITLE
translate.py only return one translation while k=5

### ISSUE THREAD

**Issue by amirj** [nyu-dl/dl4mt-cdec#3]
I'm trying to translate using a trained model using `translate.py`. The problem is that `translate.py` writes only one translation in the output file while I set `k=5`. 
After checking the source code, it seems that `_translate` function [only returns the best translation](https://github.com/nyu-dl/dl4mt-cdec/blob/master/character_base/translate.py#L44) among different available translations.

**Comment by jych** [comment]
Hi, the translate.py script returns the best translated results using the beam search. So if you want all the other results along with the best one, you can copy/modify the script and make your own version.

**Comment by amirj** [comment]
Ahaa, k is the Beam Size not the number of possible outputs!
Thanks for your quick answer.
